// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mopvrwmdcdqrqybuyeng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcHZyd21kY2RxcnF5YnV5ZW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTE4NTMsImV4cCI6MjA3MzkyNzg1M30.BnjS4ahM2d45aVknR6L4Uh-_-CW0VwaTSoqGAZtRFWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});